const DEFAULT_CARET_SIZE = 10;
const DEFAULT_TOOLTIP_OFFSET = 0;
const DEFAULT_SCREEN_PADDING = 4;
const DEFAULT_BORDER_RADIUS = 12;
const DEFAULT_PLACEMENT = 'top';
const DEFAULT_ON_PRESS_ACTION_TYPE = 'onPress';
const DEFAULT_TOOLTIP_BACKGROUND = '#FFFFFF';
const DEFAULT_BACKDROP_COLOR = 'rgba(0,0,0,0.5)';

const DEFAULT_SAFE_AREA_INSETS = {
  top: 0,
  right: 0,
  bottom: 0,
  left: 0,
};

export {
  DEFAULT_CARET_SIZE,
  DEFAULT_SAFE_AREA_INSETS,
  DEFAULT_TOOLTIP_OFFSET,
  DEFAULT_SCREEN_PADDING,
  DEFAULT_BORDER_RADIUS,
  DEFAULT_PLACEMENT,
  DEFAULT_ON_PRESS_ACTION_TYPE,
  DEFAULT_TOOLTIP_BACKGROUND,
  DEFAULT_BACKDROP_COLOR,
};
